# Site settings
title: DRAGen - Discrete RVE Automation and Generation
description: A brief description of your site
url: https://ibf-RWTH.github.io/DRAGen
baseurl: "" # The base URL of your site. Leave it empty if you are publishing to the root.

# Build settings
markdown: kramdown
theme: minima # Use a theme for your site. You can change this to other supported themes.

# Exclusions
exclude:
  - README.md # Exclude files or directories from the build

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-feed

# Social links
social:
  twitter: 
  github: https://github.com/ibf-RWTH
  linkedin: https://www.linkedin.com/company/ibf-der-rwth-aachen-university/mycompany/

# Other settings
paginate: 10 # Number of posts per page if using pagination

"""
title: The title of your site.
description: A brief description of your site.
url: The URL where your site will be published. Replace username and repository with your GitHub username and repository name.
baseurl: The subpath of your site (if it’s not in the root directory). Leave it empty if you’re using the root directory.
theme: Specify a theme for your site. You can choose from themes available on GitHub Pages or create a custom theme.
exclude: List files or directories to exclude from the build.
plugins: Add plugins to extend Jekyll’s functionality. Note that GitHub Pages has a specific set of supported plugins.
social: Add your social media links if you want them displayed.
paginate: Configure pagination if your site has multiple pages.

Adding Jekyll theme;
theme: jekyll-theme-minima

Advanced cinfiguration:
Navigation Links:
nav:
  - Home: /
  - About: /about
  - Contact: /contact

https://jekyllrb.com/docs/

Sample by jekyll:

# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: Sample Jekyll Blog

# Short description (goes below the title; it will also be used in the RSS feed)
description: This is a sample Jekyll Blog.

# Your name, as you want it to appear underneath each post and in the footer
author: Your Name

# Your email if you want it to be linked on the contact page
author_email: you@example.com

# The directory for category index pages. Change it to something else if
# for example you want links like /categories/category1 instead of /category1
category_dir: /

# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
#baseurl: /path/to/blog 
baseurl: 

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: http://yourdomain.com/

#### Under the Hood Stuff #####

# Use rdiscount as the markdown engine because it generates html5 compliant code for stuff like footnotes
# If you use maroku (default engine) some of your generated pages may not validate or lint as html5
# If you don't have it install it via gem install rdiscount
markdown: rdiscount

# Makes pretty (descriptive) permalinks. See Jekyll docs for alternatives.
permalink: pretty

# How many articles do you wish to appear on the front page:
paginate: 3

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]

# Listing gems used by project
gems: [jekyll-paginate]
"""