# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "Austenite" ]
  pull_request:
    branches: [ "Austenite" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest==8.2.2
    - name: Print environment variables
      run: printenv    
    - name: Print working directory
      run: pwd
    - name: Print current directory contents
      run: ls -al
    - name: Check memory usage
      run: |
        free -h
    - name: Test with test cases
      run: |
        pytest -vv Test_Cases/run_all_test_cases.py
        #python DRAGen_testcases.py
    - name: Upload core dump if tests fail
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: core-dump
        path: core.*
